### ISSUE TITLE
how to uninstall this theme completely?

### ISSUE THREAD

**Issue by azamet90** [daniruiz/flat-remix-gnome#117]
gsettings set org.gnome.shell.extensions.user-theme name "Flat-Remix"  after giving this command for one theme my all themes are littlebit moved how to revert this?
i mean my all shell themes are so broken

**Comment by daniruiz** [comment]
Did you install the theme from the package/`make install` or just copied it to /usr/share/themes or ~/.themes?

If just copied it then, LOL this is weird
Otherwise, if you made a full installation then... This could be the explanation
Installing a gnome-shell theme doesn't replace the default one but overrides some of its styles. By installing the complete flat-remix-gnome theme does replace the default theme, as it is the only way to change the login theme. But that does different themes to work weird, as they are designed to work over the vanilla one. If you want to use other gnome-shell themes you will need to restore the file that was overrided in the installation of flat-remix-gnome theme but then you will also lose the login theme
To restore it you can
* If it is Ubuntu just logout and select the default ubuntu session instead of Flat-Remix*
* Rest of distros reinstall the gnome-shell package

**Comment by azamet90** [comment]
> Did you install the theme from the package/`make install` or just copied it to /usr/share/themes or ~/.themes?
> 
> If just copied it then, LOL this is weird
> Otherwise, if you made a full installation then... This could be the explanation
> Installing a gnome-shell theme doesn't replace the default one but overrides some of its styles. By installing the complete flat-remix-gnome theme does replace the default theme, as it is the only way to change the login theme. But that does different themes to work weird, as they are designed to work over the vanilla one. If you want to use other gnome-shell themes you will need to restore the file that was overrided in the installation of flat-remix-gnome theme but then you will also lose the login theme
> To restore it you can
> 
>     * If it is Ubuntu just logout and select the default ubuntu session instead of Flat-Remix*
> 
>     * Rest of distros reinstall the gnome-shell package

i dont remember how i did uninstall it but i did uninstall it theme looks good but there is some moved places on your theme like navbar for example if you release an update for the navbar the theme will looks better dash to panel breaks little bit after install it
