### ISSUE TITLE
weird shell top bar

### ISSUE THREAD

**Issue by mqssi** [daniruiz/flat-remix-gnome#197]
![image](https://user-images.githubusercontent.com/43760122/159014430-4ef9e013-8601-4206-8983-639738a2b660.png)

I'm having this weird visual bug, is there any known fix yet ?

**Comment by LouisDISPA** [comment]
I have it, it's not a fix but i switched to the fullPanel version which has a better visual, especially with a blurred background.

**Comment by mqssi** [comment]
Yes i've done the same in the meantime theres a fix.

@daniruiz Is there a safe way to completly uninstall the theme ?

**Comment by daniruiz** [comment]
This is a bug caused by the gnome-shell extension that adds the blur to the panel. There's nothing I can do to fix it. But the full-panel version of the theme does work properly with the extension 

To uninstall the theme run `sudo make uninstall` inside the folder of flat-remix-gnome you downloaded
