### ISSUE TITLE
Update for GNOME 47

### ISSUE THREAD

**Issue by siddhpant** [daniruiz/flat-remix-gnome#232]
Please update for gnome 47. For example, they changed button styles so using flat remix makes buttons weird.

![Screenshot from 2024-10-19 15-28-17](https://github.com/user-attachments/assets/2a44dd83-f852-4743-9156-776f103f48b3)

**Comment by gnolooo** [comment]
Other issues as well, for example sliders have one small white dot:

![image](https://github.com/user-attachments/assets/805f2da0-0e4f-4563-981f-7fb35689e506)

Also, I know this is not related to this Gnome Shell theme itself, and more to the Flat Remix project in general, but GDM is kinda broken sometimes.

**Comment by siddhpant** [comment]
Nvm, fixed by pulling latest repo.

Extremely sorry for the noise, didn't see the new commits.

**Comment by siddhpant** [comment]
The GTK theme needs to be fixed though as it has the same problem.

**Comment by siddhpant** [comment]
> GDM is kinda broken sometimes.

How? Though I use GDM Settings app to set the wallpaper after updating.

**Comment by gnolooo** [comment]
Is there a GDM Settings app? I use `set-gdm-theme`, part of [`gdm-tools`](https://github.com/realmazharhussain/gdm-tools), to set the theme and the wallpaper. I believe it does the same thing though, it's just a script.
The theme is broken because of the same reasons (buttons and sliders, as you and I have already highlighted). Also, it randomly happens another issue, weird to describe: all the grphical elements (buttons etc) disappear, and there's only plain, black, small, glitched text. I can still login normally (type the password and then Enter), but it's there. Unfortunately I'm unable to reproduce it and acquire screenshots. This only happens when the theme is outdated, though. Hence why I said that Flat Remix GDM needs a Gnome 47 refresh too.

**Comment by siddhpant** [comment]
> Is there a GDM Settings app?

It's a flathub app you can see.


> The theme is broken because of the same reasons (buttons and sliders, as you and I have already highlighted).
> 
> This only happens when the theme is outdated, though. Hence why I said that Flat Remix GDM needs a Gnome 47 refresh too.

The theme is already updated as I said earlier, please pull latest master.
