### ISSUE TITLE
Support for Window List Extension

### ISSUE THREAD

**Issue by thomasreiser** [daniruiz/flat-remix-gnome#58]
I am using the "Window List" extension that can be enabled in the GNOME Tweaks program.
Unfortunately, the style of that window list does not match the style of the Flat Remix theme:

![screenshot from 2018-12-24 09-10-00](https://user-images.githubusercontent.com/170543/50394158-d183b980-075b-11e9-9e74-ba51fdc084c6.png)

Is it possible to modify the styles also for that window list at the bottom?

**Comment by daniruiz** [comment]
Don't know why but after some tests I'm not able to modify the app button background. It always remains black (or white for classic gnome desktop). It is weird because I can change the text background but not the rest of the element, I've even tried tricking it by using some shadows but it doesn't look good.

I'm sorry but I think I can do nothing here :disappointed:
