### ISSUE TITLE
Login interface after lock screen does not same with login.

### ISSUE THREAD

**Issue by shafiqruslan** [daniruiz/flat-remix-gnome#78]
Hello, it's pretty weird because when i want to login after lockscreen it is default ubuntu theme but when i login for the first time it use a flat-remix theme ? can i know why?

**Comment by andrewc910** [comment]
Same issue. Ubuntu 18.04. Tested on 2 different laptops(same version). Pretty much, first time logging in is the beautiful remix login. After suspending, all subsequent logins are ubuntu default(ugly purple) login. Is this a limitation or a bug? Hopefully just a bug!

**Comment by daniruiz** [comment]
It should work fine out of the box. You can select the login screen theme by running `sudo update-alternatives --config gdm3.css`. This command let's you change the login theme from the installed ones (only on Ubuntu).
If you don't see my theme there then just remove and reinstall the theme from the ppa, so that it correctly runs this script https://github.com/daniruiz/flat-remix-gnome/blob/master/deb/flat-remix-gnome-3.32.2/debian/postinst

**Comment by g1e2n04** [comment]
Same issue on my Ubuntu 18.04, however in my case, it was because I did not change the theme of a shell.

I used GNOME Tweaks to change the theme, and I changed only the `Applications` theme. However, the greeter/login screen and the lock screen are seems to be independent. It seems necessary to change the shell theme.

The shell theme change is locked default, so I installed the following extensions.
```
sudo apt install gnome-shell-extensions
```

After changing the shell theme, it works fine with the lock screen.

**Comment by gwjczwy** [comment]
I have the same issue.And i had used `sudo update-alternatives --config gdm3.css` in my terminal.But not use.

**Comment by daniruiz** [comment]
Try to clone this repository and run `make && sudo make install`

**Comment by gjvpaet** [comment]
@andrewc910's solution worked for me.
