### ISSUE TITLE
Ubuntu 18/19 support ?!

### ISSUE THREAD

**Issue by theraw** [daniruiz/flat-remix-gnome#81]
Hello,

i really like this theme before i had ubuntu 18.10 everything was working well sometimes ex in google chrome i wasn't able to see the "minimize" button for chrome window, after restarts or log out sometimes was here sometimes nope.

Anyway now i have ubuntu 19.04 and that chrome window problem is still here, isn't a big problem however i saw a new problem desktop > right click ex "New folder" option is not there :confused: and some more are missing

So i was thinking to ask if you support or have any plan for ubuntu 19, (Gnome 3.32.1), i tried "Flat Remix Dark "

Thank you.

**Comment by daniruiz** [comment]
The theme already supports Ubuntu 19.04. The issue about the "New folder" menu is because after installing this theme it enables default gnome. Ubuntu by default comes with some gnome extensions, for example, desktop icons, which are disabled by default.
So you just need to re-enable them, that simple :smile:  You can do it so by opening gnome-tweaks (I think it isn't installed on Ubuntu by default) and there you can find some advanced options for your desktop. Inside extensions enable desktop icons and it should work again.
If you want you can download other extensions here https://extensions.gnome.org/ and customize even more your linux :grin:

About chrome issue, chrome can't be affected by gnome's theme, can you send me a screenshot by the way?

**Comment by theraw** [comment]
well it seems like is full support.. even the chrome problem, i don't understand why sometimes was there and sometimes wasn't however in ubuntu 19 wasn't so i started to record a video to show you but during that time i found 
![image](https://user-images.githubusercontent.com/32969774/57183483-df85db80-6ead-11e9-9095-c66f0350667a.png)

So that problem seems fixed now
